// frontend/src/components/organisms/ProjectCard.tsx
import Button from "@/components/atoms/Button";
import Chip from "@/components/atoms/Chip";
import MonoGlyph from "@/components/atoms/MonoGlyph";
import ExternalLink from "@/components/atoms/ExternalLink";
import type { Project } from "@/types/portfolio";

export default function ProjectCard({ project }: { project: Project }) {
  if (project.variant === "featured") {
    return (
      <div className="mb-6 grid overflow-hidden rounded-[18px] border border-line bg-surface/45 backdrop-blur-[14px] md:grid-cols-2">
        <div className="p-8 sm:p-11">
          <div className="mb-[18px] flex items-center gap-2.5">
            <span className="rounded-md border border-signal/30 px-2 py-1 font-mono text-[11px] text-signal">{project.badge}</span>
            <span className="font-mono text-[11px] text-muted">live</span>
          </div>
          <h3 className="mb-3.5 text-3xl font-bold tracking-tight">{project.title}</h3>
          <p className="mb-[22px] text-[15.5px] leading-relaxed text-paper/60">{project.description}</p>
          <div className="mb-[26px] flex flex-wrap gap-2">
            {project.tags.map((t) => <Chip key={t} variant="tech">{t}</Chip>)}
          </div>
          <Button href={project.href} className="px-[18px] py-2.5">Visit live ↗</Button>
        </div>
        <div className="flex min-h-[260px] items-center justify-center border-t border-line bg-[repeating-linear-gradient(135deg,rgba(242,169,59,0.06)_0,rgba(242,169,59,0.06)_14px,transparent_14px,transparent_28px)] md:border-l md:border-t-0">
          <div className="text-center font-mono text-xs text-muted">
            <MonoGlyph className="mb-2 block text-[26px] opacity-55">◳</MonoGlyph>
            project_shot.png
          </div>
        </div>
      </div>
    );
  }
  return (
    <div className="rounded-2xl border border-line bg-surface/40 p-7 backdrop-blur-[14px]">
      <div className="mb-4 flex items-start justify-between">
        <MonoGlyph className="text-[22px] opacity-70">{"{ }"}</MonoGlyph>
        <span className="rounded border border-line px-2 py-0.5 font-mono text-[10.5px] text-muted">{project.badge}</span>
      </div>
      <h3 className="mb-2 text-[19px] font-semibold">{project.title}</h3>
      <p className="mb-4 text-sm leading-relaxed text-paper/55">{project.description}</p>
      <div className="mb-4 flex flex-wrap gap-[7px]">
        {project.tags.map((t) => <Chip key={t} variant="muted">{t}</Chip>)}
      </div>
      <ExternalLink href={project.href} className="font-mono text-[13px] text-signal">Visit ↗</ExternalLink>
    </div>
  );
}

// frontend/app/components/ProjectCard.vue
<script setup lang="ts">
import type { ProjectItem } from '../stores/portfolio';
import { usePortfolioStore } from '../stores/portfolio';

const props = defineProps<{
  project: ProjectItem;
}>();

const store = usePortfolioStore();

const isSaved = computed(() => store.isBookmarked(props.project.id));

const tagsList = computed(() =>
  props.project.tags ? props.project.tags.split(',').map((t) => t.trim()) : [],
);
</script>

<template>
  <div
    class="rounded-xl border border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-900 p-6 flex flex-col justify-between shadow-sm hover:shadow-md transition-shadow duration-200"
  >
    <div>
      <div class="flex items-start justify-between gap-2 mb-3">
        <div class="flex items-center gap-2 flex-wrap">
          <h3 class="text-lg font-bold text-gray-900 dark:text-white">
            {{ project.title }}
          </h3>
          <span
            v-if="project.featured"
            class="text-xs px-2 py-0.5 rounded-full font-medium bg-amber-100 dark:bg-amber-950 text-amber-800 dark:text-amber-300"
          >
            Featured
          </span>
        </div>

        <!-- Pinia-driven bookmark button -->
        <button
          type="button"
          class="p-1.5 rounded-lg text-gray-400 hover:text-amber-500 dark:hover:text-amber-400 transition-colors"
          :title="isSaved ? 'Remove Bookmark' : 'Bookmark Project'"
          @click="store.toggleBookmark(project.id)"
        >
          <span v-if="isSaved" class="text-amber-500 font-bold">★</span>
          <span v-else class="text-gray-400">☆</span>
        </button>
      </div>

      <p class="text-sm text-gray-600 dark:text-gray-400 mb-4 leading-relaxed">
        {{ project.description }}
      </p>

      <div class="flex flex-wrap gap-1.5 mb-6">
        <span
          v-for="tag in tagsList"
          :key="tag"
          class="text-xs px-2 py-0.5 rounded bg-gray-100 dark:bg-gray-800 text-gray-700 dark:text-gray-300 font-medium"
        >
          {{ tag }}
        </span>
      </div>
    </div>

    <div class="pt-4 border-t border-gray-100 dark:border-gray-800 flex items-center justify-between gap-3">
      <div class="flex items-center gap-2">
        <a
          v-if="project.demoUrl"
          :href="project.demoUrl"
          target="_blank"
          rel="noopener noreferrer"
          class="text-xs font-semibold text-emerald-600 dark:text-emerald-400 hover:underline"
        >
          Live Demo &rarr;
        </a>
        <a
          v-if="project.githubUrl"
          :href="project.githubUrl"
          target="_blank"
          rel="noopener noreferrer"
          class="text-xs font-semibold text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white"
        >
          Source Code
        </a>
      </div>

      <span class="text-xs text-gray-400">
        ID #{{ project.id }}
      </span>
    </div>
  </div>
</template>
